User.create(firstname: 'Michael', lastname: 'Adams', email: 'michael@email.com', birthday: '1902-11-21', password:'12345', username:'michael')

User.create(firstname: 'Peter', lastname: 'Rabbit', email: 'peter@email.com', birthday: '1904-3-21', password:'12345', username:'peter')

User.create(firstname: 'Aragorn', lastname: 'Strider', email: 'aragorn@email.com', birthday: '1321-12-29', password:'12345', username:'aragorn')

Post.create(hypothetical: "If you had a horn that was the size of a 500ml Coca Cola bottle that was anywhere on your body, where would you place it? It is incredibly strong and durable so no surgery can remove it.",user_id: 1)
Post.create(hypothetical: "Would you rather box an Uruk-Hai or wrestle an orc?",user_id: 3)
Post.create(hypothetical: "Would you rather never have to sleep or never have to use the bathroom?",user_id: 1)
Post.create(hypothetical: "zxv1sldkfja",user_id: 1)
Post.create(hypothetical: "serwrldkfja",user_id: 1)
Post.create(hypothetical: "sGJDFDKLldkfja",user_id: 1)
Post.create(hypothetical: "mdklsfjldfsldkfja",user_id: 1)
Post.create(hypothetical: "If you had to have your arms be twice their current length or your legs be twice their current length. Which would you choose?",user_id: 1)
Post.create(hypothetical: "If your partner asked you to drink polyjuice potion occasionally would you be offended?",user_id: 1)
Post.create(hypothetical: "grewa",user_id: 1)
Post.create(hypothetical: "yuooewrsldkfja",user_id: 1)
Post.create(hypothetical: "popldjflkssldkfja",user_id: 1)
Post.create(hypothetical: "ja",user_id: 1)
Post.create(hypothetical: "sfdkfja",user_id: 1)
Post.create(hypothetical: "098897",user_id: 1)
Post.create(hypothetical: "sldkfja",user_id: 1)
Post.create(hypothetical: "sdfsa",user_id: 1)
Post.create(hypothetical: "If you could be completely fluent in five languages which would you choose? (You would forget any language you know now)",user_id: 1)
