User.create(firstname: 'Jack', lastname: 'Frost', email: 'jack@email.com', birthday: '1902-11-21', password:'12345', username:'jack')

User.create(firstname: 'Peter', lastname: 'Rabbit', email: 'peter@email.com', birthday: '1904-3-21', password:'12345', username:'peter')

User.create(firstname: 'Aragorn', lastname: 'Strider', email: 'aragorn@email.com', birthday: '1321-12-29', password:'12345', username:'aragorn')

Post.create(hypothetical: "sldkfja",user_id: 1)
Post.create(hypothetical: "slfd",user_id: 1)
Post.create(hypothetical: "yrtsldkfja",user_id: 1)
Post.create(hypothetical: "zxv1sldkfja",user_id: 1)
Post.create(hypothetical: "serwrldkfja",user_id: 1)
Post.create(hypothetical: "sGJDFDKLldkfja",user_id: 1)
Post.create(hypothetical: "mdklsfjldfsldkfja",user_id: 1)
Post.create(hypothetical: "78329832sldkfja",user_id: 1)
Post.create(hypothetical: "s7893ldkfja",user_id: 1)
Post.create(hypothetical: "grewa",user_id: 1)
Post.create(hypothetical: "yuooewrsldkfja",user_id: 1)
Post.create(hypothetical: "popldjflkssldkfja",user_id: 1)
Post.create(hypothetical: "ja",user_id: 1)
Post.create(hypothetical: "sfdkfja",user_id: 1)
Post.create(hypothetical: "098897",user_id: 1)
Post.create(hypothetical: "sldkfja",user_id: 1)
Post.create(hypothetical: "sdfsa",user_id: 1)
Post.create(hypothetical: "98776544a",user_id: 1)
